name: my_flutter_portfolio
description: An online portfolio built entirely in Flutter for web.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.9
  connectivity_plus_web: ^1.2.5
  device_info_plus: ^6.0.0
  device_info_plus_web: ^5.0.0
  dio: ^4.0.6
  file_local_storage_inspector: ^0.3.1
  firebase_analytics: ^10.1.0
  firebase_analytics_web: ^0.5.1+8
  firebase_core: ^2.4.1
  firebase_core_web: ^2.1.0
  firebase_crashlytics: ^3.0.10
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^7.0.1
  flutter_secure_storage_web: ^1.1.1
  flutter_svg: ^1.1.6
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.2.0
  get_x_navigation_generator_annotations: ^0.0.5
  icapps_architecture: ^0.8.1
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  niddler_dart: ^1.6.0
  path: ^1.8.2
  path_provider: ^2.0.11
  preferences_local_storage_inspector: ^0.3.1
  provider: ^6.0.5
  retrofit: ^3.3.1
  scroll_when_needed: ^2.0.0
  secure_storage_local_storage_inspector: ^0.5.0
  shared_preferences: ^2.0.16
  shared_preferences_web: ^2.0.4
  sprintf: ^7.0.0
  sqlite3_flutter_libs: ^0.5.12
  storage_inspector: ^0.3.0
  synchronized: ^3.0.1
  url_launcher: ^6.1.7
  universal_io: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.4.1
  get_x_navigation_generator: ^0.0.7
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  icapps_license: ^2.0.2

  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  license_generator: ^1.0.5
  mockito: ^5.3.2
  model_generator: ^6.0.2
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf

license_generator:
  check_before_generate: true